---
- name: addingvlans
  hosts: leafs
  tasks:
    - name: ensure vlans exist
      loop: "{{ global_vlans }}"
      eos_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item['name'] }}"
            state: active
        state: merged

  